from typing import Dict, List, Optional


# ============================================================
# SAMPLE FORENSIC CASES
# ============================================================
#
# These are demo/reference cases used by TRUVENA.
#
# IMPORTANT:
# - Do NOT import sample_data from itself.
# - Dynamic unknown clusters are handled by forensic_engine.py.
# - Case B intentionally represents an unknown generator pattern.
#
# ============================================================

SAMPLE_FORENSIC_CASES: List[Dict] = [

    # ========================================================
    # CASE A — KNOWN GENERATOR: FLUX
    # ========================================================
    {
        "id": "case_flux_001",
        "name": "FLUX Synthetic Portrait",
        "description": "Synthetic portrait generated by a known FLUX-family generator.",

        "classification": "AI Generated",
        "ai_probability": 96,
        "real_probability": 4,

        "likely_generator": "FLUX",
        "generator_confidence": 94,

        "risk_level": "HIGH",
        "trust_score": 4,

        "evidence_level": "HIGH",

        "classifier_ai_probability": 97.5,
        "forensic_score": 94.2,

        "forensic_signals": {
            "frequency": 93.4,
            "residual": 91.8,
            "texture": 95.1,
            "entropy": 92.7,
            "edge": 94.5
        },

        "media_dna_match": 94,
        "media_dna_novelty": 6,

        "cluster_id": None,
        "cluster_status": None,

        "c2pa": {
            "status": "Not Found",
            "verified": False
        },

        "watermark": {
            "status": "Unavailable",
            "detected": False
        },

        "explanation": (
            "Multiple forensic signals are strongly consistent with "
            "synthetic media. The Media DNA profile closely matches "
            "the known FLUX generator signature."
        ),

        "evidence": [
            "High AI classifier signal",
            "Strong frequency-domain anomalies",
            "Synthetic texture characteristics",
            "Strong Media DNA match with FLUX",
            "No verified provenance found"
        ],

        "dna_vector": {
            "frequency": 0.934,
            "residual": 0.918,
            "texture": 0.951,
            "compression": 0.927,
            "semantic": 0.945,
            "artifact": 0.936,
            "generator": 0.940
        }
    },


    # ========================================================
    # CASE B — UNKNOWN / EMERGING GENERATOR
    # ========================================================
    #
    # This case is intentionally NOT assigned a fake cluster
    # such as "UNKNOWN CLUSTER #47".
    #
    # forensic_engine.py creates the dynamic U-001, U-002...
    # cluster when this case is analyzed.
    #
    # ========================================================
    {
        "id": "case_unknown_001",
        "name": "Unknown Generator Sample",
        "description": (
            "Synthetic media exhibiting a recurring forensic pattern "
            "that is not currently associated with a known generator."
        ),

        "classification": "Uncertain",
        "ai_probability": 78,
        "real_probability": 22,

        "likely_generator": "UNKNOWN",
        "generator_confidence": 0,

        "risk_level": "HIGH",
        "trust_score": 22,

        "evidence_level": "MEDIUM",

        "classifier_ai_probability": 86.5,
        "forensic_score": 69.8,

        "forensic_signals": {
            "frequency": 73.2,
            "residual": 68.7,
            "texture": 71.5,
            "entropy": 66.4,
            "edge": 69.1
        },

        "media_dna_match": 0,
        "media_dna_novelty": 100,

        "cluster_id": None,
        "cluster_status": "NEW_UNKNOWN_PATTERN",

        "c2pa": {
            "status": "Not Found",
            "verified": False
        },

        "watermark": {
            "status": "Unavailable",
            "detected": False
        },

        "explanation": (
            "The image contains strong synthetic-media indicators, "
            "but its Media DNA does not sufficiently match any "
            "currently registered generator. TRUVENA treats it as "
            "a potential unknown generator pattern."
        ),

        "evidence": [
            "Elevated AI classifier signal",
            "Distinct frequency-domain characteristics",
            "Synthetic residual pattern",
            "No strong match against known generator registry",
            "Potential unknown generator pattern"
        ],

        "dna_vector": {
            "frequency": 0.732,
            "residual": 0.687,
            "texture": 0.715,
            "compression": 0.664,
            "semantic": 0.691,
            "artifact": 0.703,
            "generator": 0.000
        }
    },


    # ========================================================
    # CASE C — KNOWN GENERATOR: MIDJOURNEY
    # ========================================================
    {
        "id": "case_midjourney_001",
        "name": "Midjourney Synthetic Artwork",
        "description": "Synthetic artwork matching a known Midjourney Media DNA pattern.",

        "classification": "AI Generated",
        "ai_probability": 91,
        "real_probability": 9,

        "likely_generator": "Midjourney",
        "generator_confidence": 89,

        "risk_level": "HIGH",
        "trust_score": 9,

        "evidence_level": "HIGH",

        "classifier_ai_probability": 93.1,
        "forensic_score": 88.4,

        "forensic_signals": {
            "frequency": 89.2,
            "residual": 86.7,
            "texture": 91.4,
            "entropy": 87.5,
            "edge": 88.9
        },

        "media_dna_match": 89,
        "media_dna_novelty": 11,

        "cluster_id": None,
        "cluster_status": None,

        "c2pa": {
            "status": "Not Found",
            "verified": False
        },

        "watermark": {
            "status": "Unavailable",
            "detected": False
        },

        "explanation": (
            "Forensic characteristics strongly indicate synthetic "
            "media. The extracted Media DNA closely matches the "
            "registered Midjourney pattern."
        ),

        "evidence": [
            "High AI classifier signal",
            "Strong synthetic texture characteristics",
            "Frequency-domain anomalies detected",
            "High Media DNA similarity to Midjourney",
            "No verified provenance found"
        ],

        "dna_vector": {
            "frequency": 0.892,
            "residual": 0.867,
            "texture": 0.914,
            "compression": 0.875,
            "semantic": 0.889,
            "artifact": 0.881,
            "generator": 0.890
        }
    },


    # ========================================================
    # CASE D — AUTHENTIC / REAL IMAGE
    # ========================================================
    {
        "id": "case_real_001",
        "name": "Authenticated Real Photograph",
        "description": (
            "Reference photograph exhibiting characteristics "
            "consistent with naturally captured imagery."
        ),

        "classification": "Likely Real",
        "ai_probability": 12,
        "real_probability": 88,

        "likely_generator": "UNKNOWN",
        "generator_confidence": 0,

        "risk_level": "LOW",
        "trust_score": 88,

        "evidence_level": "HIGH",

        "classifier_ai_probability": 14.5,
        "forensic_score": 18.2,

        "forensic_signals": {
            "frequency": 16.4,
            "residual": 19.7,
            "texture": 17.3,
            "entropy": 21.2,
            "edge": 16.5
        },

        "media_dna_match": 0,
        "media_dna_novelty": 0,

        "cluster_id": None,
        "cluster_status": None,

        "c2pa": {
            "status": "Verified",
            "verified": True
        },

        "watermark": {
            "status": "Unavailable",
            "detected": False
        },

        "explanation": (
            "The image shows low synthetic-media signals and forensic "
            "characteristics consistent with naturally captured imagery. "
            "Verified provenance further increases confidence in its authenticity."
        ),

        "evidence": [
            "Low AI classifier signal",
            "Low forensic synthetic-media score",
            "Natural texture distribution",
            "No known synthetic generator match",
            "Verified provenance available"
        ],

        "dna_vector": {
            "frequency": 0.164,
            "residual": 0.197,
            "texture": 0.173,
            "compression": 0.212,
            "semantic": 0.165,
            "artifact": 0.181,
            "generator": 0.000
        }
    },


    # ========================================================
    # CASE E — KNOWN GENERATOR: SDXL
    # ========================================================
    {
        "id": "case_sdxl_001",
        "name": "SDXL Synthetic Scene",
        "description": "Synthetic scene matching a known Stable Diffusion XL pattern.",

        "classification": "AI Generated",
        "ai_probability": 88,
        "real_probability": 12,

        "likely_generator": "Stable Diffusion XL",
        "generator_confidence": 86,

        "risk_level": "HIGH",
        "trust_score": 12,

        "evidence_level": "HIGH",

        "classifier_ai_probability": 90.4,
        "forensic_score": 84.7,

        "forensic_signals": {
            "frequency": 85.6,
            "residual": 82.9,
            "texture": 87.1,
            "entropy": 83.4,
            "edge": 84.8
        },

        "media_dna_match": 86,
        "media_dna_novelty": 14,

        "cluster_id": None,
        "cluster_status": None,

        "c2pa": {
            "status": "Not Found",
            "verified": False
        },

        "watermark": {
            "status": "Unavailable",
            "detected": False
        },

        "explanation": (
            "The image contains multiple synthetic-media indicators "
            "and its Media DNA shows a strong similarity to the "
            "registered Stable Diffusion XL pattern."
        ),

        "evidence": [
            "High AI classifier signal",
            "Synthetic frequency characteristics",
            "Elevated residual anomalies",
            "High Media DNA similarity to SDXL",
            "No verified provenance found"
        ],

        "dna_vector": {
            "frequency": 0.856,
            "residual": 0.829,
            "texture": 0.871,
            "compression": 0.834,
            "semantic": 0.848,
            "artifact": 0.842,
            "generator": 0.860
        }
    }
]


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def get_sample_cases() -> List[Dict]:
    """
    Return all available forensic sample cases.
    """

    return SAMPLE_FORENSIC_CASES


def get_sample_by_id(sample_id: str) -> Optional[Dict]:
    """
    Return a sample case by its ID.

    Returns:
        Dict if the sample exists.
        None if the sample does not exist.
    """

    if not sample_id:
        return None

    for sample in SAMPLE_FORENSIC_CASES:
        if sample.get("id") == sample_id:
            return sample

    return None